---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker
#
# tasks file for netdata

# Manage base system packages [[[1
- name: Ensure base packages are in there desired state
  package:
    name: '{{ item }}'
    state: '{{ "present" if (netdata__deploy_state == "present") else "absent" }}'
    install_recommends: '{{ netdata__install_recommends | bool }}'
  with_flattened:
    - '{{ netdata__base_packages }}'


